name: TribeMobile
options:
  bundleIdPrefix: com.madewithtribe
  deploymentTarget:
    iOS: 17.0
settings:
  base:
    DEVELOPMENT_TEAM: "Z2RT4J42R5"
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
targets:
  TribeMobile:
    type: application
    platform: iOS
    sources:
      - path: Sources/TribeMobile
      - path: Resources/HeritageSerif.ttf
        buildPhase: resources
    resources:
      - path: Resources/Assets.xcassets
      - path: Sources/TribeMobile/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.madewithtribe.mobile
        INFOPLIST_FILE: Resources/Info.plist
        MARKETING_VERSION: 0.1.0
        CURRENT_PROJECT_VERSION: 14
    preBuildScripts: []